name: deploy
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    needs: build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "secret-transfer"
          heroku_email: "4at-nk@mail.ru"